### ISSUE TITLE
[pip install] Missing VERSION file

### ISSUE THREAD

**Issue by hanchao** [openmaptiles/openmaptiles-tools#11]
```
$ pip install openmaptiles-tools
Collecting openmaptiles-tools
  Using cached openmaptiles-tools-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cUsPLW/openmaptiles-tools/setup.py", line 5, in <module>
        version=open('VERSION').read(),
    IOError: [Errno 2] No such file or directory: 'VERSION'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cUsPLW/openmaptiles-tools/
```

**Comment by ImreSamu** [comment]
@hanchao :  Thank you for reporting!  

workaround:  temporary you can use the `pip install .`  method!  as in [openmaptiles-tools/Dockerfile.py27](https://github.com/openmaptiles/openmaptiles-tools/blob/master/Dockerfile.py27)

**Comment by lukasmartinelli** [comment]
Try again now. I removed version/readme file so it is pip installable again.

**Comment by ImreSamu** [comment]
@lukasmartinelli :
* alternative fix method - create a `MANIFEST.in` file - see N4 :  https://packaging.python.org/single_source_version/
* because the travis test using the VERSION file :  https://travis-ci.org/openmaptiles/openmaptiles-tools

**Comment by lukasmartinelli** [comment]
Just looking at the travis test.

What does checklist the `checklist.chk` actually verify?
The checksums only verify that the Python2 and Python3 are the same right?
But every time something changes we would need to rewrite "the test" (like in #8).

**Comment by ImreSamu** [comment]
>The checksums only verify that the Python2 and Python3 are the same right?

yes,  

* the first version of `generate-etlgraph` have written the output to the `openmaptiles/layers/*/*.png`  so I modified for **"overwrite only if the content is have changed"** - for better git logs ..
* and after I realized some python2 - python3  differences and different text outputs ..  so I have to find a p2/p3 compatible solutions ...  
* probably an overdesign,   you can refactor as you like..

**Comment by ImreSamu** [comment]
>But every time something changes we would need to rewrite "the test" (like in #8).

yes ...

**Comment by MartinMikita** [comment]
This should be fixed now. New updated version is on [pypi](https://pypi.org/project/openmaptiles-tools/) as well.
