### ISSUE TITLE
generate-imposm3, append tags > include

### ISSUE THREAD

**Issue by frodrigo** [openmaptiles/openmaptiles-tools#179]
If a layer define 
```yaml
tags:
    include: [...]
```
It override the default. It should append the included tags.

https://github.com/openmaptiles/openmaptiles-tools/blob/master/openmaptiles/imposm.py#L58

**Comment by nyurik** [comment]
@frodrigo could you give a complete example of a layer with the tags? E.g. a PR to modify https://github.com/openmaptiles/openmaptiles-tools/blob/master/tests/testlayers/housenumber/mapping.yaml ? And also how that would change https://github.com/openmaptiles/openmaptiles-tools/blob/master/tests/expected/imposm3.yaml ?  Thanks!
