### ISSUE TITLE
Make borders and wikidata cachable and able to import from backup

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles-tools#194]
* We should be able to import current (new) borders from PBF, but also import from backup CSV 
* The same principle with wikidata - Use Wikidata Quering Service for updates and new queries, but also able to import pre-cached, backup data. 

Borders are in CSV, wikidata maybe in SQLite

**Comment by TomPohys** [comment]
PR #191 

it has to be tested out.

**Comment by TomPohys** [comment]
wd:Q24282857 redirect to Q27463211 
or
Q7375562 redirect to Q13045182

Second run import-wikidata (to add wikidata from ```place layer```) read a file correctly and try again search for wikidata. But these ```wd:Q25299623 wd:Q7375562 ``` are redirected. 

It could be used as a problem data detection.

```bash
Found 389 Wikidata IDs, -387 in cache, 2 new
Deleting any existing data in wd_names...
Copying 387 Wikidata IDs from cache...
Finished inserting 387 Wikidata IDs from cache into wd_names table
Query Wikidata Service for 2 IDs...
----------
    SELECT ?id ?label WHERE {
      VALUES ?id { wd:Q25299623 wd:Q7375562 }
      ?id rdfs:label ?label.
    }
----------
Finished inserting 2 Wikidata IDs from WDQS into wd_names table
Saving 387 items to cache place.json
```

**Comment by nyurik** [comment]
@TomPohys I fixed the handling of the redirecst -- now it queries wikidata, and whatever it doesn't find, it queries for redirects, and tries again.

I propose we discuss bugs in a PR like this on the PR itself -- keeps things together in one place. :)
