### ISSUE TITLE
Unable to generate-metadata with multiple mbtiles files

### ISSUE THREAD

**Issue by mattjhammond** [openmaptiles/openmaptiles-tools#197]
Last year we had an older version of the docker image, I believe 0.9.2 but I'm not quite sure, and we're able to generate-metadata with a 51GB map file.  Using the latest release I get an error.  I've tested the older and latest release with another smaller mbtiles file with the same results.  It appears to be some sort of issue parsing the boundary.

I have no name!@f9781ef35978:/usr/src/app$ generate-metadata /tileset/test.mbtiles
Traceback (most recent call last):
  File "/usr/src/app/generate-metadata", line 118, in <module>
    main(docopt(__doc__, version=openmaptiles.__version__, options_first=True))
  File "/usr/src/app/generate-metadata", line 91, in main
    bbox = Bbox(bbox=os.environ.get('BBOX'),
  File "/usr/src/app/openmaptiles/utils.py", line 28, in __init__
    self.min_lon = float(left)
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by nyurik** [comment]
Could you double check that BBOX environment variable is defined?

**Comment by mattjhammond** [comment]
BBOX is not defined.  What should the value be?  I should be able to pass that in as a temporary fix.

**Comment by nyurik** [comment]
The BBOX is defined in the `.env` file, or it could get overridden by the docker compose file that gets generated during the extract download.  If you run it by hand, you should provide the bbox of your data.

**Comment by mattjhammond** [comment]
I didn't need this information before.  I was given an mbtiles file of the entire planet and instructions to run the generation.
docker run -it --rm -u $(id -u ${USER}):$(id -g ${USER}) -v /host-folder/:/tileset openmaptiles/openmaptiles-tools generate-metadata ./osm-2017-07-03-v3.6.1-planet.mbtiles

This worked fine.
How do I get and set the BBOX environment value?

**Comment by nyurik** [comment]
you can use `--env-file <file>`, e.g. `--env-file .env`, or you can set it explicitly - `-e "BBOX=..."`
