### ISSUE TITLE
Postserve cache?

### ISSUE THREAD

**Issue by andrestone** [openmaptiles/openmaptiles-tools#198]
High there!

I'm thinking that maybe having a simple "cache" system to reuse the MVT's generated by the postserve queries would be a good thing to have. That would be as simple as storing the MVT's somewhere as static files, which would eventually be served directly instead of querying the database again.

Is this a desirable feature or it's out of the project's scope? Maybe it already exists and I'm so lazy that I couldn't find it?

**Comment by nyurik** [comment]
There are two types of cache one could have: internal (postserve would keep a cache of the recently used tiles, possibly in a shared redis-like ), and external (i.e. reverse proxy) - a service that would cache postserve responses.  I would rather use the reverse proxy -- no point to reimplement what has already been done well.  I would advise using [Varnish](https://www.varnish-cache.org/) - a well known and fast cache.

One more thing to keep in mind -- postserve is not a "production oriented" system. Perhaps some day it will be, with additional capabilities for logging, monitoring, stability and security reviews, ..., but for now it is mostly created for testing.

**Comment by frodrigo** [comment]
Same point of view as @nyurik .

You can look this https://github.com/makinacorpus/makina-maps/tree/master/nginx I implement it with nginx, including the cache invalidation from imposm update.

**Comment by andrestone** [comment]
Thank you so much for the quick reply. 

In my specific case, I guess it would be more cost effective to simply store the MVTs in a cheap storage service (such as S3) and serve those as static files, somehow managing invalidation due to imposm update.

What I'm trying to say (and maybe it only applies for my usual infrastructure which is always cloud based) is that this strategy would save me more resources at a much lower cost, and would probably feel fast enough.

Thanks for the suggestions!

**Comment by nyurik** [comment]
If you want, you can always store tiles as individual files on S3, without any special server infrastructure. AFAIK, that's what Mapbox does as well.  It does cost though - as you end up with billions of small files in an S3 bucket.

**Comment by andrestone** [comment]
It's maybe worth a doing some math but I think that storing MVTs and therefore having some sort of data redundancy is cheaper than calculating these MVTs every time we need to render them. Maybe I should filter which tiles to store based on request frequency.

**Comment by nyurik** [comment]
Sure, retrieving a ready-made tile vs re-generating it is far faster, so in terms of a performance, from fastest to slowest:
* a CDN edge server to returned the needed tile from local cache
* centralized caching server (e.g. Varnish) to return the data from cache
* tile server getting the pre-generated data from a local stoarge (this could be a file or a PostgreSQL table with pre-made blobs)
* tile server generating the tile from imposm-generated tables.

The pregenerated method that stores tiles in a table might be the most efficient approach, as it is shared between multiple tile servers (load balancing), and could be regenerated locally. It can be easily implemented with a materialized view.

**Comment by andrestone** [comment]
Could be, the question is if the overall added blob size in a DB instance is really cheaper than a simple S3 or even an S3 behind a CDN.

**Comment by nyurik** [comment]
direct serving from S3 should be faster than serving from a database -- simply by the fact that S3 (or Google's GCP, or Azure ...) will be highly optimized for direct distributed storage serving, possibly with CDN support.  But as I said - it may cost you considerably more to store that many small objects in S3, especially due to the fact that most of them will be identical (e.g. water or empty land)

**Comment by andrestone** [comment]
Thanks for all the info. But could you please explain why should I consider storing these objects on S3 to be more expensive than storing the correspondent blob objects in Postgres?
