### ISSUE TITLE
imposm3 job split strategy?

### ISSUE THREAD

**Issue by andrestone** [openmaptiles/openmaptiles-tools#199]
Hi,

I'm trying to find a way to split the imposm3 job into as many extracts as possible (per country / per state). I know I can split the *building cache* phase with the `-appendcache` option, but it seems like the `-write` option always overwrites the data in the database, meaning that this phase can't be split.

Is there any good / known method to achieve this? My goal is to have smaller jobs to build a database from a full planet.

Maybe an imposm fork somewhere?

Thanks.

**Comment by TomPohys** [comment]
Hi @andrestone,

What I know, imposm3 do not have a function like this. Openmaptiles import whole planet or a smaller extract and import pbf whole at once.
