### ISSUE TITLE
generate-tm2source ignores the PG environment variables

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles-tools#202]
Unlike other tools, `generate-tm2source` ignores the PG environment variables and requires the PG connection information to be passed as parameters.

```
$ docker-compose run --rm openmaptiles-tools generate-tm2source openmaptiles.yaml
Traceback (most recent call last):
  File "/usr/src/app/generate-tm2source", line 26, in <module>
    port=int(args['--port']),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by zstadler** [comment]
This is probably why openmaptiles' Makefile has the connections hard-coded 

```
docker-compose run $(DC_OPTS) openmaptiles-tools generate-tm2source openmaptiles.yaml --host="postgres" --port=5432 --database="openmaptiles" --user="openmaptiles" --password="openmaptiles" > $@
```

rather leverage the settings in the `.env` file.

If this issue is fixed, https://github.com/openmaptiles/openmaptiles/pull/795 is no longer needed.

**Comment by nyurik** [comment]
@zstadler fixed in ^
