### ISSUE TITLE
`osmborder` aborts on openstreetmap.fr extracts

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles-tools#215]
`osmborder` aborts when its input is an extract downloaded from [openstreetmap.fr](http://download.openstreetmap.fr/extracts/)

### Error Message
```
terminate called after throwing an instance of 'osmium::not_found'
  what():  location for one or more nodes not found in node location index
```

### Analysis
Note: 14-Apr-20 edits are marked **in bold below**
- The error message suggests that the input file contains references to nodes that are located outside of the extraction polygon.
   ```
   $ docker-compose run --rm openmaptiles-tools osmborder /import/borders/filtered.pbf -o /dev/null
   terminate called after throwing an instance of 'osmium::not_found'
     what():  location for one or more nodes not found in node location index
   ```
- `osmborder` succeeds if **before running `osmborder_filter`** the input file is fixed using  
**`osmconvert --drop-broken-refs -b=-180,-90,180,90`**.</br>
   <b>
   ```
   $ docker-compose run --rm openmaptiles-tools osmconvert --drop-broken-refs -b=-180,-90,180,90 -o=/import/borders/monaco.osm.pbf /import/monaco.osm.pbf

   $ docker-compose run --rm openmaptiles-tools osmborder_filter -o /import/borders/filtered.pbf /import/borders/monaco.osm.pbf

   $ docker-compose run --rm openmaptiles-tools osmborder -o /import/borders/lines.csv /import/borders/filtered.pbf
   There were 0 warnings.
   There were 0 errors.

   $ docker-compose run --rm openmaptiles-tools wc -l /import/borders/lines.csv
   72 /import/borders/lines.csv
   ```
   </b>

### To Reproduce
In an [`openmaptiles`](https://github.com/openmaptiles/openmaptiles) installation run:
```
rm -f data/*.pbf
docker-compose run --rm openmaptiles-tools bash -c 'download-osm osmfr europe/vatican_city -- -d /import'
make import-borders
```

Output:
```
$ rm -fr data

$ docker-compose run --rm openmaptiles-tools bash -c 'download-osm osmfr europe/vatican_city -- -d /import'
Unable to load md5 hash for europe/vatican_city from http://download.openstreetmap.fr/extracts/europe/vatican_city-latest.osm.pbf: Received status=404
Downloading http://download.openstreetmap.fr/extracts/europe/vatican_city-latest.osm.pbf (size=0.5 MB (488,724), md5=None)

  aria2c --http-accept-gzip "--user-agent=OpenMapTiles download-osm 4.1.0 (https://github.com/openmaptiles/openmaptiles-tools)" -d /import http://download.openstreetmap.fr/extracts/europe/vatican_city-latest.osm.pbf


04/13 07:40:06 [NOTICE] Downloading 1 item(s)
[#49af17 304KiB/477KiB(63%) CN:1 DL:368KiB]
04/13 07:40:08 [NOTICE] Download complete: /import/vatican_city-latest.osm.pbf

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
49af17|OK  |   468KiB/s|/import/vatican_city-latest.osm.pbf

Status Legend:
(OK):download completed.

$ make import-borders
docker-compose up -d postgres
openmaptiles_postgres_1 is up-to-date
Wait for PostgreSQL to start...
docker-compose run --rm import-osm ./pgwait.sh
docker-compose run --rm openmaptiles-tools import-borders
Filtering /import/vatican_city-latest.osm.pbf into /import/borders/filtered.pbf
Creating a CSV borders file /import/borders/lines.csv
terminate called after throwing an instance of 'osmium::not_found'
  what():  location for one or more nodes not found in node location index
/usr/src/app/import-borders: line 75:    23 Aborted                 osmborder -o "$BORDERS_CSV_FILE" "$BORDERS_PBF_FILE"
Makefile:158: recipe for target 'import-borders' failed
make: *** [import-borders] Error 134
```

#### Note
This new issue was opened in this repository because it uses a specific version of [osmborder](https://github.com/pnorman/osmborder)
   https://github.com/openmaptiles/openmaptiles-tools/blob/4ed919770276a1aad949c7ddfe4bbfa0b68e3196/Dockerfile#L12

**Comment by nyurik** [comment]
CCing @pnorman as I think this should be a feature of the [osmborder](https://github.com/pnorman/osmborder) code

**Comment by nyurik** [comment]
The e3ae8f7a2dcdcd6dc80abab4679cb5edb7dc6fa5 is the current master of the `osmborder`.  I did not want to use `master` as that can be updated at any moment.

**Comment by zstadler** [comment]
Give that
- [osmborder](https://github.com/pnorman/osmborder) is an archived read-only repository
- Openmaptiles' `boundary` layer already uses `imposm3` to receive OSM data

I wonder if a better solution to this issue would be to drop the use of osmborder and use imposm3 instead.

In this approach the schema graph for the  `boundary` layer would be

![no-import-borders](https://user-images.githubusercontent.com/1304610/79309455-fed11980-7f02-11ea-88db-46366c7fa051.png)

Instead of of the current schema graph

![import-borders](https://user-images.githubusercontent.com/1304610/79309625-45bf0f00-7f03-11ea-9064-daa6cdcd3601.png)

This change would include:
- Removing the `claimed_by: [__any__]` filter from the `osm_border_disp_relation` mapping definition
- Defining the `disputed` field as `true` if `claimed_by` is non-empty
- Renaming and removing layers as shown in the proposed schema graph
- Simplifying the layer's SQL code

**Comment by nyurik** [comment]
As I wrote in Slack, I'm all for it, assuming we can generate a similar osmborder lines directly in SQL. As a first step, I suggest we do not alter the SQL structure (per images above), but instead try to generate identical tables using SQL-only method.  If successful, then the next step would be to optimize the tables.
