### ISSUE TITLE
Workflow of openmaptiles

### ISSUE THREAD

**Issue by exotfboy** [openmaptiles/openmaptiles-tools#22]
Hi:

I am not exactly sure the working process of openmaptiles.

Since I found most of the sources codes here are sql scripts, and I wonder how do you serve the tile data for a given tile coordinate?

**Comment by klokan** [comment]
https://github.com/openmaptiles/openmaptiles/#prepare-the-database

Generating of the tiles happens in ```docker-compose run generate-vectortiles```
which means code at:
https://github.com/openmaptiles/generate-vectortiles
and esp.
https://github.com/openmaptiles/generate-vectortiles/blob/master/export-local.sh#L16

Serving happens with a tileserver later on.
