### ISSUE TITLE
can't read /tmp/project/data.yml: No such file or directory

### ISSUE THREAD

**Issue by adad4cast** [openmaptiles/openmaptiles-tools#289]
docker-compose -f docker-compose.yml -f ./data/docker-compose-config.yml  run --rm generate-vectortiles

WARNING: The TOOLS_VERSION variable is not set. Defaulting to a blank string.
WARNING: The BBOX variable is not set. Defaulting to a blank string.
WARNING: The FILTER_MAPNIK_OUTPUT variable is not set. Defaulting to a blank string.
WARNING: The MAX_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The MIN_ZOOM variable is not set. Defaulting to a blank string.
WARNING: The DIFF_MODE variable is not set. Defaulting to a blank string.
sed: can't read /tmp/project/data.yml: No such file or directory

**Comment by nyurik** [comment]
Does your directory have `.env` file?

**Comment by adad4cast** [comment]
Yes. 

PGHOST=127.0.0.1
PGDATABASE=osm
PGUSER=osm
PGPASSWORD=osm

**Comment by nyurik** [comment]
Please take a look at the current version of the openmaptiles's [.env](https://github.com/openmaptiles/openmaptiles/blob/master/.env) and [.env-postgres](https://github.com/openmaptiles/openmaptiles/blob/master/.env-postgres)

**Comment by adad4cast** [comment]
Thanks a lot, @nyurik.
