### ISSUE TITLE
0.9.2 wheel uses /usr/bin/python3 in shebang

### ISSUE THREAD

**Issue by Phyks** [openmaptiles/openmaptiles-tools#29]
Hi,

The code for the scripts in the `bin` directory uses [`#!/usr/bin/env python3`](https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/generate-imposm3#L1) which makes it easier to run within a python virtualenv for instance.

However, when `pip`-installing `openmaptiles-tools` (using the 0.9.2 wheel), the scripts use `#!/usr/bin/python3`), which breaks when running within a virtual env.

This can be easily verified by unzipping https://files.pythonhosted.org/packages/b5/48/2d5ff0fbaa59d967ad2a9eb7e697100abb5fa48688e4a51d0e1ff6797c45/openmaptiles_tools-0.9.2-py3-none-any.whl and looking at the scripts. Not exactly sure where this is coming from though :/

Thanks!

**Comment by MartinMikita** [comment]
Thanks for the notice. We would be glad to review and merge your PR changes to fix the issue.

**Comment by nyurik** [comment]
@Phyks I think all such links has been fixed a while ago. Is it safe to close this ticket?

**Comment by nyurik** [comment]
@Phyks i'll close this ticket for now, please comment if it should still be worked on. Thx!
