### ISSUE TITLE
Proxy pass to a subdirectory of a URL

### ISSUE THREAD

**Issue by 4nuragk** [openmaptiles/openmaptiles-tools#306]
I'm running the omt server in Docker in a Linux srever. I am able to access it using ip:port

I'm trying to proxy pass it to my apache subdirectory but it resolves to the main directory (/)

Example:
When i try to proxypass 172.16.x.x:8888 to https://example.com/test/openmaptiles/, it tries searching for script in https://example.com/

How do I make the openmaptiles the default directory?
Please help.

![Screenshot from 2020-08-02 15-28-22](https://user-images.githubusercontent.com/29572449/89612076-8a98f800-d89c-11ea-996e-ba6f2469eade.png)

**Comment by frodrigo** [comment]
Still, not the right project. Ask Maptiller support.
