### ISSUE TITLE
imposm doesn't respect the "replication_interval" value.

### ISSUE THREAD

**Issue by AmazingBeu** [openmaptiles/openmaptiles-tools#308]
the imposm version embedded in the openmaptiles-tools container doesn't respect the "replication_interval" value.

This was fixed in 2018 : https://github.com/omniscale/imposm3/pull/158

Use the v0.10.0 solve the issue.

**Comment by frodrigo** [comment]
Use docker image `5.2.1-imposm10` to have it.

**Comment by TomPohys** [comment]
imposm is now in version v0.11.1
