### ISSUE TITLE
import-sql error: osml10n_get_name_without_brackets_from_tags. No function matches the given name and argument types

### ISSUE THREAD

**Issue by PraneethaMoturi** [openmaptiles/openmaptiles-tools#312]

**Comment by PraneethaMoturi** [comment]
On running "./quickstart.sh asia" on the master branch, I'm getting import-sql error.

The error is 
`psql:/usr/src/app/sql/zzz_language.sql:74: ERROR:  function osml10n_get_name_without_brackets_from_tags(hstore, unknown, geometry) does not exist
LINE 9:       NULLIF(osml10n_get_name_without_brackets_from_tags(tag...
                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Time: 0.958 ms
make: *** [import-sql] Error 3
`

**Comment by frodrigo** [comment]
It defined here https://github.com/giggls/mapnik-german-l10n/blob/v2.5.9/plpgsql/get_localized_name_from_tags.sql#L230
from here https://github.com/openmaptiles/openmaptiles-tools/blob/master/docker/postgis/Dockerfile#L19-L20

Please, first check your setup with this.

**Comment by TomPohys** [comment]
Hi @PraneethaMoturi, any update on this issue? Do you still get the error?
