### ISSUE TITLE
generate-vectortiles - docker: Error response from daemon: OCI runtime create failed: container_linux.go:349

### ISSUE THREAD

**Issue by michaldolnik** [openmaptiles/openmaptiles-tools#321]
When I run the command `docker run -v $(pwd):/tileset openmaptiles/openmaptiles-tools generate-vectortiles` i am getting the error `docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"generate-vectortiles\": executable file not found in $PATH": unknown.`

Does somebody experience the same error?

**Comment by TomPohys** [comment]
Hi @michaldolnik, are you try to run `make generate-tiles area=*` from the OpenMapTiles project? Mention in https://github.com/openmaptiles/openmaptiles-tools#usage-with-docker

**Comment by TomPohys** [comment]
Hi @michaldolnik, were you successful with running `generate-vectortiles`?

**Comment by michaldolnik** [comment]
Hi @TomPohys sorry, but I did not tried it so far...

**Comment by TomPohys** [comment]
Please, try https://github.com/openmaptiles/openmaptiles#develop and the easiest way how to start is `./quickstart.sh`

**Comment by TomPohys** [comment]
Hi @michaldolnik, do you have some more insight into this problem?

**Comment by michaldolnik** [comment]
Sorry. I haven't come back to that. I think you can close this issue as it's not verified I think...
