### ISSUE TITLE
Unable to download Germany from Geofabrik

### ISSUE THREAD

**Issue by TomPohys** [openmaptiles/openmaptiles-tools#327]
There is an ID for Germany in https://download.geofabrik.de/index-v1.json (`"id" : "germany"`) but `./quickstart.sh germany`, `./quickstart.sh germany geofabrik` is unable to download Germany. 

The only possible is `./quickstart.sh europe/germany` which is downloaded from OsmFr.

Please @nyurik, do you have any idea why Germany is not possible to download? France, Great Britain, Czech Republic are OK

https://github.com/openmaptiles/openmaptiles/issues/1001

**Comment by TomPohys** [comment]
Today's test was OK and `./quickstart.sh germany` runs OK. So, there is no bug in the OpenMapTiles or OpenMapTiles-Tools projects. Thanks

**Comment by msschl** [comment]
Having the same issue...

But I am unable to download `europe/germany` and `germany`. Both give the following error:
```
Unable to auto-detect the source for 'germany'
Makefile:312: recipe for target 'download-geofabrik' failed
```
