### ISSUE TITLE
generate-vectortiles no longer builds

### ISSUE THREAD

**Issue by etresoft** [openmaptiles/openmaptiles-tools#346]
npm ERR! Linux 5.4.0-70-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "tl@0.8.1" "mapnik@3.5.13" "mbtiles@0.8.2" "tilelive@5.12.2" "tilelive-tmsource@0.5.0" "tilelive-vector@3.9.3" "tilelive-bridge@2.3.1" "tilelive-mapnik@0.6.18"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:12)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:456:7
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm http 200 https://registry.npmjs.org/js-yaml
npm info retry fetch attempt 1 at 6:29:28 PM
npm info attempt registry request try #1 at 6:29:28 PM
npm http fetch GET https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz
npm http fetch 200 https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz
npm http 200 https://registry.npmjs.org/mapnik-reference
npm info retry fetch attempt 1 at 6:29:28 PM
npm info attempt registry request try #1 at 6:29:28 PM
npm http fetch GET https://registry.npmjs.org/mapnik-reference/-/mapnik-reference-8.10.0.tgz
npm http 200 https://registry.npmjs.org/carto
npm http fetch 200 https://registry.npmjs.org/mapnik-reference/-/mapnik-reference-8.10.0.tgz
npm info retry fetch attempt 1 at 6:29:28 PM
npm info attempt registry request try #1 at 6:29:28 PM
npm http fetch GET https://registry.npmjs.org/carto/-/carto-0.14.1.tgz
npm http fetch 200 https://registry.npmjs.org/carto/-/carto-0.14.1.tgz

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by TomPohys** [comment]
It looks like some error with npm. If I build from `generate-vectortiles` from the cache, it works.

**Comment by TomPohys** [comment]
It looks like `hash -d npm` should solve something (https://askubuntu.com/questions/1036278/npm-is-incorrect-version-on-latest-ubuntu-18-04-installation)

or https://github.com/npm/cli/issues/681#issuecomment-820882457

but I am not an expert on npm

**Comment by TomPohys** [comment]
Solved by update packages (#347)
