### ISSUE TITLE
Remove Python 2

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles-tools#35]
I would like to propose we remove anything Python2 related from this (and other) repos.  Python 2 will not be supported beyond the end of this year. IMO, there is really no point in keeping this thing alive.  Are there any reasons we shouldn't do it already?  Thx!

**Comment by MartinMikita** [comment]
Hi @nyurik!

Yes, we definitely agree! We are not aware of any reason, why it shouldn't be done.

We would be very grateful for your contributions and to merge your PRs.

**Comment by nyurik** [comment]
Done as part of https://github.com/openmaptiles/openmaptiles-tools/pull/36 , please +1

**Comment by nyurik** [comment]
Closing as done
