### ISSUE TITLE
Dockerfile build error

### ISSUE THREAD

**Issue by duongnv1989** [openmaptiles/openmaptiles-tools#352]
Hi. Thanks for the great library.
When I try to build docker, I get an error as shown below. Why such an error?
We hope to receive an answer. Thanks.

![image](https://user-images.githubusercontent.com/15391082/127130235-627e0546-a1a8-426e-b468-cee94f260ee8.png)

**Comment by TomPohys** [comment]
Hi, 
it seams that you missing `python3` in your windows system.

Nevertheless, I recommend building docker under WSL2 (Windows Subsystem for Linux). Some steps by step in https://github.com/openmaptiles/openmaptiles/issues/1095#issuecomment-817099375

**Comment by duongnv1989** [comment]
@TomPohys 
Thank you very much. I tried as your suggestion and amazingly it ran successfully.
