### ISSUE TITLE
output run_last.sql is empty?

### ISSUE THREAD

**Issue by duongnv1989** [openmaptiles/openmaptiles-tools#353]
Hi.
My aim is to generate MVT data from PBF data source.
I use `generate-sql` tool to generate SQL statements to execute in PostGIS, but check the output there is `run_last.sql` file with empty content.
Here is my command: 
`docker run -it --rm -v "D:\OSM\openmaptiles:/tileset" -v "D:\OSM\import:/import" -v "D:\OSM\export:/export" -v "D:\OSM\mapping:/mapping" -v "D:\OSM\cache:/cache" -v "D:\OSM\sql:/sql" -e POSTGRES_HOST="172.17.0.2" -e POSTGRES_DB="openmaptiles" -e POSTGRES_USER="openmaptiles" -e POSTGRES_PASSWORD="openmaptiles" openmaptiles/openmaptiles-tools generate-sql openmaptiles.yaml --dir /sql`
When I use `generate-tile` tool command I get this error:
![image](https://user-images.githubusercontent.com/15391082/127427766-4ed4d25c-226b-4797-9a80-8d463f103492.png)

Am I doing something wrong?
Waiting for the answer. Thanks.

**Comment by duongnv1989** [comment]
I used `generate-sqltomvt` and it ran:
`docker run -it --rm  -v "D:\OSM\openmaptiles:/tileset" -v "D:\OSM\import:/import" -v "D:\OSM\mapping:/mapping" -v "D:\OSM\cache:/cache" -v "D:\OSM\export:/export" -v "D:\OSM\sql:/sql" -e PGHOST="172.17.0.2" -e PGDATABASE="openmaptiles" -e PGUSER="openmaptiles" -e PGPASSWORD="openmaptiles" openmaptiles/openmaptiles-tools generate-sqltomvt openmaptiles.yaml --function --fname=getmvt > D:\OSM\sql\run_last.sql`

**Comment by TomPohys** [comment]
Thanks for the comment with the solution.
