### ISSUE TITLE
Build fail for import-data docker image

### ISSUE THREAD

**Issue by ache051** [openmaptiles/openmaptiles-tools#366]
Build fail for the last few days due to Natural Earth's download service being down or removed: https://www.naturalearthdata.com/downloads/. With the download links on Natural Earth's website striked-thru, it can be certain that the NE team is either aware of the issue or the change was deliberate.
Issue is also submitted in NE's repo: https://github.com/nvkelso/natural-earth-vector/issues/577

Suggestion for fix:
Natural Earth data is curated on AWS' Open Data Registry: https://registry.opendata.aws/naturalearth/. The issue can be fixed if line 11 of the Dockerfile:
https://github.com/openmaptiles/openmaptiles-tools/blob/4dfdc1ab1ccdb0475cd94ebd8570fc255e3f8024/docker/import-data/Dockerfile#L11
is changed to:
wget --quiet https://naturalearth.s3.amazonaws.com/packages/natural_earth_vector.sqlite.zip  ;\

**Comment by nyurik** [comment]
i'm all for migrating to that link (thx!)

**Comment by nyurik** [comment]
@ache051 can you create a PR for this?  Don't want to take credit for your research :)

**Comment by ache051** [comment]
Done :)
