### ISSUE TITLE
Docker is not auto-building

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles-tools#37]
Despite saying that this repo is being auto-built by docker (at the top of the README), it really is not building automatically.

See https://hub.docker.com/r/openmaptiles/openmaptiles-tools/builds -- it says `This repository doesn't have any autobuilds`.

Please update the `latest` to automatically build from the master.

CC: @klokan (not sure who else has access rights to the docker repo)

**Comment by MartinMikita** [comment]
Hi Yuri,
sorry for delay. There were some changes in docker hub system, which broke the existing configuration.
We have fixed now each openmaptiles repositories to work with autobuild system.
The new `latest` is now in the queue for building form the recent master (5761050 commit).

We will close, when the new docker image would be available.

**Comment by MartinMikita** [comment]
A new docker image has been built and published.

**Comment by nyurik** [comment]
@MartinMikita thanks for fixing it!  Does it automatically pick up the new tags too? (I will want to release a more stable v0.10 shortly)

**Comment by MartinMikita** [comment]
Yes, if you create a release, it will create a docker image with tag (removing the first character `v`).
