### ISSUE TITLE
Use PostgreSQL 11+ to benefit from parallel "CREATE TABLE AS" ?

### ISSUE THREAD

**Issue by alex-kowalczyk** [openmaptiles/openmaptiles-tools#396]
Docs for PostgreSQL 11+ state that 
> As an exception, the commands `CREATE TABLE ... AS`, `SELECT INTO`, and `CREATE MATERIALIZED VIEW` that create a new table and populate it can use a parallel plan.
-- https://www.postgresql.org/docs/12/when-can-parallel-query-be-used.html

A long-running create operation which ends long after all other parallelized queries, like `CREATE TABLE IF NOT EXISTS osm_transportation_name_network AS`, might benefit from running on parallel plan. 

Is it considered to move openmaptiles postgres image to newer version in near future? 
If not, would you have any suggestions for creating customized alternate image? Especially, is in general expected that current codebase will work fine with newer PostgreSQL versions, or there are some things known to not work fine (beside the `-c jit=off` thing)?

**Comment by TomPohys** [comment]
Thanks for pointing this out. The plan is to upgrade to the newest PostgreSQL 14.

**Comment by TomPohys** [comment]
PostgreSQL upgraded in https://github.com/openmaptiles/openmaptiles-tools/pull/413.
