### ISSUE TITLE
Travis setup 

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles-tools#5]
The [.travis](https://github.com/openmaptiles/openmaptiles-tools/blob/master/.travis.yml)  files exists ..
but I don't have sufficient rights to enable this repo on Travis.

**Comment by ImreSamu** [comment]
@lukasmartinelli -   is it possible to enable travis - here ?

**Comment by klokan** [comment]
Done:
https://travis-ci.org/openmaptiles/openmaptiles-tools

(we may need to reenable, once the github account is turned into organization)

**Comment by ImreSamu** [comment]
@klokan : Thanx - I have fixed some travis problems .. - now it is OK ... 

[![Build Status](https://api.travis-ci.org/openmaptiles/openmaptiles-tools.svg?branch=master)](https://travis-ci.org/openmaptiles/openmaptiles-tools)
